### ISSUE TITLE
Quarterly histogram and CSV broken

### ISSUE THREAD

**Issue by misaochan** [whym/commons-app-stats#14]
Hi @whym , the quarterly histogram appears to be broken. CSV file has lots of "NoName"s and "NoTitle"s too.

Sorry to bother but it's the stats time of the year again. :)

**Comment by whym** [comment]
I spent some time checking the logs and the only thing I found was that recently queries just timed out. I need some more time to investigate.

**Comment by misaochan** [comment]
Thanks @whym , we really appreciate it. :) Could you please ping me when it's fixed?

**Comment by misaochan** [comment]
Hey @whym , does https://phabricator.wikimedia.org/T244786 help with this?

**Comment by whym** [comment]
Done in f71f6f8e! (I think) @misaochan 

About T244786 - I think the Anomie's comment "Toolforge's replica views simulate rev_comment_id" applies here. I haven't encountered an error saying 'rev_comment_id' is not found.

**Comment by misaochan** [comment]
@whym Great news, thanks!! The histogram works for me. :) Any idea why the edits are so much higher starting 2019 Q3 though? Are we adding new uploads to "edits" after that time frame, maybe?

**Comment by whym** [comment]
I took a look at https://commons.wikimedia.org/wiki/Special:RecentChanges?hidebots=1&translations=filter&hidecategorization=1&hideWikibase=1&tagfilter=android+app+edit&limit=50&days=7&urlversion=2 and there are many edits to captions like https://commons.wikimedia.org/w/index.php?title=File:Map_of_the_Lop_Nor_region_by_Folke_Bergman_1935.jpg&curid=1165657&diff=396578833&oldid=151873509 . Do you think these should be excluded (or separately counted)?

**Comment by misaochan** [comment]
@whym Strange, it seems to be broken again today, I only see the 2015 bars again. Yet I don't see any new commits that could've caused it. I tried clearing my cache and viewing it on a different browser but the problem persists. Does it look broken to you?

**Comment by misaochan** [comment]
```
Exception: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: '\nSELECT /* SLOW_OK */ rev_timestamp, actor_name, page_title, rev_parent_id\nFROM revision\n   JOIN comment ON rev_comment_id = comment_id\n   JOIN actor ON rev_actor = actor_id\n   JOIN page ON rev_page = page_id\n WHERE (EXISTS (SELECT * FROM change_tag WHERE ct_rev_id = rev_id AND ct_tag_id = 22) /* ="Android app edit" */\n    OR comment_text LIKE "%%Via Commons Mobile App%%"\n    OR comment_text LIKE "%%using Android Commons%%"\n    OR comment_text LIKE "%%COM:MOA%%")\n AND rev_timestamp >= "20191210" AND rev_timestamp < "20200218"\nORDER BY rev_timestamp DESC\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
Exception: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: '\nSELECT /* SLOW_OK */ rev_timestamp, actor_name, page_title, rev_parent_id\nFROM revision\n   JOIN comment ON rev_comment_id = comment_id\n   JOIN actor ON rev_actor = actor_id\n   JOIN page ON rev_page = page_id\n WHERE (EXISTS (SELECT * FROM change_tag WHERE ct_rev_id = rev_id AND ct_tag_id = 22) /* ="Android app edit" */\n    OR comment_text LIKE "%%Via Commons Mobile App%%"\n    OR comment_text LIKE "%%using Android Commons%%"\n    OR comment_text LIKE "%%COM:MOA%%")\n AND rev_timestamp >= "20191211" AND rev_timestamp < "20200219"\nORDER BY rev_timestamp DESC\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
Exception: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: '\nSELECT /* SLOW_OK */ rev_timestamp, actor_name, page_title, rev_parent_id\nFROM revision\n   JOIN comment ON rev_comment_id = comment_id\n   JOIN actor ON rev_actor = actor_id\n   JOIN page ON rev_page = page_id\n WHERE (EXISTS (SELECT * FROM change_tag WHERE ct_rev_id = rev_id AND ct_tag_id = 22) /* ="Android app edit" */\n    OR comment_text LIKE "%%Via Commons Mobile App%%"\n    OR comment_text LIKE "%%using Android Commons%%"\n    OR comment_text LIKE "%%COM:MOA%%")\n AND rev_timestamp >= "20200102" AND rev_timestamp < "20200122"\nORDER BY rev_timestamp DESC\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
Exception: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: '\nSELECT /* SLOW_OK */ rev_timestamp, actor_name, page_title, rev_parent_id\nFROM revision\n   JOIN comment ON rev_comment_id = comment_id\n   JOIN actor ON rev_actor = actor_id\n   JOIN page ON rev_page = page_id\n WHERE (EXISTS (SELECT * FROM change_tag WHERE ct_rev_id = rev_id AND ct_tag_id = 22) /* ="Android app edit" */\n    OR comment_text LIKE "%%Via Commons Mobile App%%"\n    OR comment_text LIKE "%%using Android Commons%%"\n    OR comment_text LIKE "%%COM:MOA%%")\n AND rev_timestamp >= "20191215" AND rev_timestamp < "20200104"\nORDER BY rev_timestamp DESC\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
Exception: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: '\nSELECT /* SLOW_OK */ rev_timestamp, actor_name, page_title, rev_parent_id\nFROM revision\n   JOIN comment ON rev_comment_id = comment_id\n   JOIN actor ON rev_actor = actor_id\n   JOIN page ON rev_page = page_id\n WHERE ((EXISTS (SELECT * FROM change_tag WHERE ct_rev_id = rev_id AND ct_tag_id = 22) /* ="Android app edit" */\n       AND NOT EXISTS (SELECT * FROM change_tag WHERE ct_rev_id = rev_id AND ct_tag_id = 434)) /* ="Suggested Edits edit */\n    OR comment_text LIKE "%%Via Commons Mobile App%%"\n    OR comment_text LIKE "%%using Android Commons%%"\n    OR comment_text LIKE "%%COM:MOA%%")\n AND rev_timestamp >= "20191216" AND rev_timestamp < "20200105"\nORDER BY rev_timestamp DESC\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by sivaraam** [comment]
The mention of timeout reminds me of the following phabricator task (which is still open):

https://phabricator.wikimedia.org/T234450

I'm not sure if it's related. Just wanted to mention it hoping it would be useful.

**Comment by whym** [comment]
I have been trying to fix #15 without making git commits, and it caused disruption.

I think mostly the recent problems are a result of https://wikitech.wikimedia.org/wiki/News/Actor_storage_changes_on_the_Wiki_Replicas#The_actor_table_seems_really_slow--so_does_comment - in short, the database infrastructure changed back in 2019 and it made queries I use slower, more likely to timeout. The queries with string matches with ``comment`` are inherently expensive to run, I had to tolerate timeout as long as it's infrequent, but recently it became more frequent. The new requirement for exclusion (#15) made it more difficult to mitigate. I'm still working on it.

**Comment by misaochan** [comment]
Thank you, @whym . If exclusion is exacerbating the problem, I think it's okay to not exclude the suggested edits for now, at least so that the tool can work. Actually, in my opinion the entire "edits" bar could be removed if it helps... I mostly just use the "new uploads", "deletes", and "overwrites" for statistics.

**Comment by whym** [comment]
>  Actually, in my opinion the entire "edits" bar could be removed if it helps... I mostly just use the "new uploads", "deletes", and "overwrites" for statistics.

Good point. I've done this for the quarterly chart. 02c459a49b8a09a6070108ac63c42c70ac30a7fe
